# -*- coding: utf-8 -*-
"""ml-leakage-pipeline

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18q0bjnMm64AiZwWciu4aaM9M-dSVTmOS
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# --- Task 1: Create synthetic dataset & Build Model ---
np.random.seed(42)
n_samples = 60
area_sqft = np.random.randint(800, 3500, n_samples)
num_bedrooms = np.random.randint(1, 6, n_samples)
age_years = np.random.randint(0, 30, n_samples)

# Price formula: base + area*0.045 + beds*6 - age*0.3 + random noise
price_lakhs = (20 + (area_sqft * 0.045) + (num_bedrooms * 6) - (age_years * 0.3) + np.random.normal(0, 5, n_samples))

df = pd.DataFrame({
    'area_sqft': area_sqft,
    'num_bedrooms': num_bedrooms,
    'age_years': age_years,
    'price_lakhs': price_lakhs
})

X = df[['area_sqft', 'num_bedrooms', 'age_years']]
y = df['price_lakhs']

model = LinearRegression()
model.fit(X, y)
predictions = model.predict(X)

print(f"Intercept: {model.intercept_:.2f}")
for feature, coef in zip(X.columns, model.coef_):
    print(f"{feature} Coefficient: {coef:.4f}")

comparison = pd.DataFrame({'Actual': y, 'Predicted': predictions})
print("\nFirst 5 Actual vs. Predicted:")
print(comparison.head())

# --- Task 2: Evaluate Model ---
mae = mean_absolute_error(y, predictions)
rmse = np.sqrt(mean_squared_error(y, predictions))
r2 = r2_score(y, predictions)

print(f"\nMAE: {mae:.2f}")
print(f"RMSE: {rmse:.2f}")
print(f"R2 Score: {r2:.2f}")

# MAE shows the average absolute error in lakhs; RMSE penalizes larger errors more heavily.
# R2 measures the proportion of variance (0 to 1) explained by the model; closer to 1 is better.

# --- Task 3: Residual Analysis ---
residuals = y - predictions
plt.figure(figsize=(8, 5))
plt.hist(residuals, bins=15, edgecolor='black', color='skyblue')
plt.title('Distribution of Residuals')
plt.xlabel('Residual Value (Error)')
plt.ylabel('Frequency')
plt.show()

"""A residual is just the difference between the actual house price and the price your model predicted.

The histogram shows how these errors are spread out.
Centered at Zero: This means on average, your predictions are correct.
Bell Shape (Normal Distribution): This means most of your errors are small (close to zero) and large mistakes are rare. It proves your model is a good fit for the data.
"""